services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    env_file:
      - FitnessTracker.Api/.env
    environment:
      - DATABASE_CONNECTION=Host=postgres;Port=5432;Database=fitness_tracker;Username=postgres;Password=postgres
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitness_tracker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
